### ISSUE TITLE
Errors in new build

### ISSUE THREAD

**Issue by ethan-haas** [kyleskom/NBA-Machine-Learning-Sports-Betting#108]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "/content/src/Predict/NN_Runner.py", line 10, in <module>
    model = load_model('Models/NN_Models/Trained-Model-ML')
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 155, in load
    model.compile(**saving_utils.compile_args_from_training_config(
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saving_utils.py", line 202, in compile_args_from_training_config
    optimizer = optimizers.deserialize(optimizer_config)
  File "/usr/local/lib/python3.8/dist-packages/keras/optimizers.py", line 95, in deserialize
    return deserialize_keras_object(
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/generic_utils.py", line 659, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/generic_utils.py", line 556, in class_and_config_for_serialized_keras_object
    raise ValueError(
ValueError: Unknown optimizer: Custom>Adam. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

**Comment by ronpysui** [comment]
getting this too

**Comment by bettingGorillas** [comment]
Same here
