### ISSUE TITLE
TypeError: weight_decay is not a valid argument, kwargs should be empty  for `optimizer_experimental.Optimizer`.

### ISSUE THREAD

**Issue by CesarCrZy** [kyleskom/NBA-Machine-Learning-Sports-Betting#117]
im getting following error when running
python3 main.py -xgb -odds=fanduel

Traceback (most recent call last):
  File "C:\Git\NBA-Machine-Learning-Sports-Betting\main.py", line 5, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "C:\Git\NBA-Machine-Learning-Sports-Betting\src\Predict\NN_Runner.py", line 11, in <module>
    ou_model = load_model("Models/NN_Models/Trained-Model-OU")
  File "C:\Users\Ventus-Tech11\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Ventus-Tech11\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 115, in _process_kwargs
    raise TypeError(
TypeError: weight_decay is not a valid argument, kwargs should be empty  for `optimizer_experimental.Optimizer`.

**Comment by Ahtessh** [comment]
use model = tensorflow.keras.models.load_model(fileName, compile=False) then model.compile(whatever settings here) This worked for me
Also make sure the version of tensor flow is same as it was for training the model that can be an issue

**Comment by oksanatkach** [comment]
So this solution works for inference but if you want to continue training the model after you load a checkpoint, you'll have to reset the optimizer during compiling and it will mess with the learning rate during further training :(
