### ISSUE TITLE
Please help, why do I get this error "Cannot parse keras metadata"

### ISSUE THREAD

**Issue by RLeeaustin** [kyleskom/NBA-Machine-Learning-Sports-Betting#138]
Please help, why do I get this error "Cannot parse keras metadata"...see below
I had to install tensorflow 2.12.0rc0 because it would install 2.11
========================================================

C:\Python\SportsBetting>python main.py -xgb -odds=fanduel
Traceback (most recent call last):
  File "C:\Python\SportsBetting\main.py", line 5, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "C:\Python\SportsBetting\src\Predict\NN_Runner.py", line 10, in <module>
    model = load_model('Models/NN_Models/Trained-Model-ML')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rleea\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rleea\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rleea\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\saved_model\load.py", line 113, in load
    raise IOError(
OSError: Cannot parse keras metadata at path Models/NN_Models/Trained-Model-ML\keras_metadata.pb: Received error: Error parsing message

**Comment by kyleskom** [comment]
Try uninstall tensorflow and doing a fresh install with 2.11

**Comment by RLeeaustin** [comment]
thank you for responding so quickly! I got it to work by installing python 3.8, I was running python 3.11 and the version of tensorflow it installs is determined by the version of python you are running, in case someone else runs into this. Thanks!!
