### ISSUE TITLE
error occurs

### ISSUE THREAD

**Issue by zybxixi** [kyleskom/NBA-Machine-Learning-Sports-Betting#14]
Hi, kyle, i'm getting this error, since i have no coding EXP, i don't know where goes wrong. Can you see the problem?
(base) C:\Users\zybxixi>C:\Users\zybxixi\Desktop\NBA-Machine-Learning-Sports-Betting-master\main.py
Traceback (most recent call last):
  File "C:\Users\zybxixi\Desktop\NBA-Machine-Learning-Sports-Betting-master\main.py", line 4, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "C:\Users\zybxixi\Desktop\NBA-Machine-Learning-Sports-Betting-master\src\Predict\NN_Runner.py", line 8, in <module>
    model = load_model('Models/NN_Models/Trained-Model-ML')
  File "C:\Users\zybxixi\anaconda3\lib\site-packages\tensorflow\python\keras\saving\save.py", line 186, in load_model
    loader_impl.parse_saved_model(filepath)
  File "C:\Users\zybxixi\anaconda3\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: Models/NN_Models/Trained-Model-ML/{saved_model.pbtxt|saved_model.pb}

**Comment by kyleskom** [comment]
Marking this issue as stale with no response.
