### ISSUE TITLE
Issue with Flask Startup (probably easy fix)

### ISSUE THREAD

**Issue by lsultana98** [kyleskom/NBA-Machine-Learning-Sports-Betting#147]
Please see below code + error. I had the same error when I was trying to run the main.py file initially through Unraid. I figured out it was due to the 'python' command using the older version of python. Using `python3 main.py -xgb -odds=fanduel` fixed the initial error. However I cannot figure out the correct way to get around the below error. I have tried `python3 -m flask run --debug --host=0.0.0.0` instead with no luck also. 

root@UNRAID:/mnt/disks/ua_appdata/appdata/nbabetting/NBA-Machine-Learning-Sports-Betting/Flask# flask run --debug --host=0.0.0.0
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.100:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 116-996-116
  File "main.py", line 77
    print(f"------------------{args.odds} odds data------------------")
                                                                     ^
SyntaxError: invalid syntax
192.168.0.101 - - [14/Mar/2023 16:50:16] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib64/python3.9/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib64/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt/disks/ua_appdata/appdata/nbabetting/NBA-Machine-Learning-Sports-Betting/Flask/app.py", line 69, in index
    fanduel = fetch_fanduel(ttl_hash=get_ttl_hash())
  File "/mnt/disks/ua_appdata/appdata/nbabetting/NBA-Machine-Learning-Sports-Betting/Flask/app.py", line 15, in fetch_fanduel
    return fetch_game_data(sportsbook="fanduel")
  File "/mnt/disks/ua_appdata/appdata/nbabetting/NBA-Machine-Learning-Sports-Betting/Flask/app.py", line 29, in fetch_game_data
    stdout = subprocess.check_output(cmd, cwd="../").decode()
  File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'main.py', '-xgb', '-odds=fanduel']' returned non-zero exit status 1.
192.168.0.101 - - [14/Mar/2023 16:50:16] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
192.168.0.101 - - [14/Mar/2023 16:50:16] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
192.168.0.101 - - [14/Mar/2023 16:50:16] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
192.168.0.101 - - [14/Mar/2023 16:50:16] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -

**Comment by NewBurLaSKing** [comment]
well! Dude, have you resolved this issue? I also encountered this issue yesterday while trying to run app.py. This issue looks cool!
