### ISSUE TITLE
AlreadyExistsError when running main.py

### ISSUE THREAD

**Issue by tyroneschiff** [kyleskom/NBA-Machine-Learning-Sports-Betting#21]
I am getting the following stack trace when I run your example:

root@ubuntu:~/NBA-Machine-Learning-Sports-Betting# python3 main.py -xgb
2021-12-23 18:21:52.542420: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-23 18:21:52.542477: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-12-23 18:21:54.185237: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "/root/NBA-Machine-Learning-Sports-Betting/src/Predict/NN_Runner.py", line 6, in <module>
    from tensorflow.keras.models import load_model
  File "/usr/local/lib/python3.8/dist-packages/keras/api/_v2/keras/__init__.py", line 10, in <module>
    from keras import __version__
  File "/usr/local/lib/python3.8/dist-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.8/dist-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/usr/local/lib/python3.8/dist-packages/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/usr/local/lib/python3.8/dist-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/usr/local/lib/python3.8/dist-packages/keras/layers/__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/usr/local/lib/python3.8/dist-packages/keras/mixed_precision/loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "/usr/local/lib/python3.8/dist-packages/keras/optimizers.py", line 26, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "/usr/local/lib/python3.8/dist-packages/keras/optimizer_v2/adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/usr/local/lib/python3.8/dist-packages/keras/optimizer_v2/optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.

**Comment by kyleskom** [comment]
Sorry for delay. Please try with python 3.9.x

**Comment by tyroneschiff** [comment]
Thanks for the response, however, with python 3.9.1 the problem persists:

admin_@cloudshell:~/NBA-Machine-Learning-Sports-Betting (eastern-seeker-338223)$ python3 main.py -xgb
2022-01-14 01:44:19.303661: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-14 01:44:19.303725: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-01-14 01:44:22.707576: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
Traceback (most recent call last):
  File "/home/admin_/NBA-Machine-Learning-Sports-Betting/main.py", line 4, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "/home/admin_/NBA-Machine-Learning-Sports-Betting/src/Predict/NN_Runner.py", line 6, in <module>
    from tensorflow.keras.models import load_model
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/api/_v2/keras/__init__.py", line 10, in <module>
    from keras import __version__
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/layers/__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/optimizers.py", line 26, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/optimizer_v2/adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/home/admin_/.local/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "/home/admin_/.local/lib/python3.9/site-packages/tensorflow/python/eager/monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "/home/admin_/.local/lib/python3.9/site-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.

**Comment by kyleskom** [comment]
This is a case of "works on my machine". Ill have to take a deeper look.

**Comment by StuckInLoop** [comment]
same issue here, on a ubuntu vm with python3.8

**Comment by michaeletro** [comment]
Same!

**Comment by kyleskom** [comment]
I was able to find this on Stackoverflow.
https://stackoverflow.com/questions/68970841/another-metric-with-the-same-name-already-exists

**Comment by StuckInLoop** [comment]
great! seems like we just need to make sure keras is the older 2.6.0 version.   (pip install keras==2.6.0) 
it will say its incompatible with the current TF version but it seems to execute the codes.  however, no the predictions or estimates shown from the calculations, it has blank values.

**Comment by instant-bqml** [comment]
This seems to have worked. However, it is taking an awfully long time to execute the very first time. Any idea on how long that should take?

**Comment by tyroneschiff** [comment]
This seems to have worked, however, I can't fully confirm as the code has been executing the very first time for a very long time. Any idea on how long that first execution should generally take?

**Comment by kyleskom** [comment]
Pr for Keras 2.6.0 has been merged. This issiue should be fixed. Closing issiue.
https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/pull/22
