### ISSUE TITLE
ValueError: Input 0 of layer "sequential" is incompatible with the layer

### ISSUE THREAD

**Issue by dunaevv** [kyleskom/NBA-Machine-Learning-Sports-Betting#237]
When Im running `python Test_Current_Season_OU.py`, I have the following error:

```
Traceback (most recent call last):
  File "Test_Current_Season_OU.py", line 31, in <module>
    predictions_array.append(model.predict(np.array([row])))
  File "/home/sony/Python/NBA-Machine-Learning-Sports-Betting/env/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_fileu_9ax6j4.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "/home/sony/Python/NBA-Machine-Learning-Sports-Betting/env/lib/python3.8/site-packages/keras/engine/training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "/home/sony/Python/NBA-Machine-Learning-Sports-Betting/env/lib/python3.8/site-packages/keras/engine/training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/sony/Python/NBA-Machine-Learning-Sports-Betting/env/lib/python3.8/site-packages/keras/engine/training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "/home/sony/Python/NBA-Machine-Learning-Sports-Betting/env/lib/python3.8/site-packages/keras/engine/training.py", line 2111, in predict_step
        return self(x, training=False)
    File "/home/sony/Python/NBA-Machine-Learning-Sports-Betting/env/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/home/sony/Python/NBA-Machine-Learning-Sports-Betting/env/lib/python3.8/site-packages/keras/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 107), found shape=(None, 105)
```

same with `python Test_Current_Season.py` -> `ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 106), found shape=(None, 104)`

How can I fix it?

**Comment by kyleskom** [comment]
This file hasn't been updated in years. I think the dataset has changed since so the input sizes arnt matching up.

**Comment by dunaevv** [comment]
> This file hasn't been updated in years. I think the dataset has changed since so the input sizes arnt matching up.

Ty Kyle
