### ISSUE TITLE
Error when running: ! python3 /content/NBA-Machine-Learning-Sports-Betting/main.py -xgb -odds=pointsbet

### ISSUE THREAD

**Issue by justuszu** [kyleskom/NBA-Machine-Learning-Sports-Betting#242]
when I run this line of code: ! python3 /content/NBA-Machine-Learning-Sports-Betting/main.py -xgb -odds=pointsbet

this error accrues: 
2023-05-05 19:27:20.115735: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-05-05 19:27:20.115772: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/content/NBA-Machine-Learning-Sports-Betting/main.py", line 7, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "/content/NBA-Machine-Learning-Sports-Betting/src/Predict/NN_Runner.py", line 11, in <module>
    model = load_model('Models/NN_Models/Trained-Model-ML-1680133120.689445')
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/saving/legacy/save.py", line 227, in load_model
    raise IOError(
OSError: No file or directory found at Models/NN_Models/Trained-Model-ML-1680133120.689445

I think this would not happen if it would not only call the library but also give the link.

**Comment by chriseling** [comment]
Use python 3.8
Best,
Chris
