### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int

### ISSUE THREAD

**Issue by xalppt** [kyleskom/NBA-Machine-Learning-Sports-Betting#277]
python3 main.py -xgb -odds=fanduel

if american_odds >= 100:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

Above is the problem I encounter when running main.py on vs code.

**Comment by xalppt** [comment]
@kyleskom  could you please help me to fix this issue as I want to prepare for the coming season please and thank you.

**Comment by tgbgb** [comment]
same for me

**Comment by Mihailoc** [comment]
I have the same problem.

**Comment by miztizm** [comment]
i have the same trouble ! 

```
python main.py -xgb -odds=fanduel
2023-09-26 21:21:39.705662: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
------------------fanduel odds data------------------
Dallas Mavericks (None) @ Minnesota Timberwolves (None)
---------------XGBoost Model Predictions---------------
Minnesota Timberwolves (62.2%) vs Dallas Mavericks: OVER None (95.8%)
---------------------Expected Value--------------------
Traceback (most recent call last):
  File "C:\NBA-Machine-Learning-Sports-Betting-master\main.py", line 132, in <module>
    main()
  File "C:\NBA-Machine-Learning-Sports-Betting-master\main.py", line 112, in main
    XGBoost_Runner.xgb_runner(data, todays_games_uo, frame_ml, games, home_team_odds, away_team_odds, args.kc)
  File "C:\NBA-Machine-Learning-Sports-Betting-master\src\Predict\XGBoost_Runner.py", line 89, in xgb_runner
    bankroll_fraction_home = bankroll_descriptor + str(kc.calculate_kelly_criterion(home_team_odds[count], ml_predictions_array[count][0][1])) + '%'
  File "C:\NBA-Machine-Learning-Sports-Betting-master\src\Utils\Kelly_Criterion.py", line 15, in calculate_kelly_criterion
    decimal_odds = american_to_decimal(american_odds)
  File "C:\NBA-Machine-Learning-Sports-Betting-master\src\Utils\Kelly_Criterion.py", line 5, in american_to_decimal
    if american_odds >= 100:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**Comment by godlike007322** [comment]
i have the same trouble

**Comment by kyleskom** [comment]
There are no games. Its trying to get odds for games that don't exist yet, try again when the season starts.
