### ISSUE TITLE
Error: RemoteDisconnected - Connection Issue when Sending HTTP Request in Get_Data.py

### ISSUE THREAD

**Issue by omerkymcu** [kyleskom/NBA-Machine-Learning-Sports-Betting#282]
Hello, I am experiencing the following issue. How can I fix this, or will you be releasing an update?

`(NBA) PS C:\NBA-Machine-Learning-Sports-Betting\src\Process-Data> python -m Get_Data
>>
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:57<00:00,  1.84s/it]
 39%|████████████████████████████████████████████████████████████████▋                                                                                                      | 12/31 [01:05<01:43,  5.43s/it] 
 11%|██████████████████▋                                                                                                                                                     | 1/9 [02:02<16:17, 122.24s/it] 
  0%|                                                                                                                                                                                 | 0/1 [02:02<?, ?it/s] 
Traceback (most recent call last):
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\urllib3\connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\miniconda3\Lib\http\client.py", line 1378, in getresponse
    response.begin()
  File "C:\Users\DELL\miniconda3\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\miniconda3\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\urllib3\connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\miniconda3\Lib\http\client.py", line 1378, in getresponse
    response.begin()
  File "C:\Users\DELL\miniconda3\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\miniconda3\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\NBA-Machine-Learning-Sports-Betting\src\Process-Data\Get_Data.py", line 57, in <module>
    general_data = get_json_data(url.format(month1, day1, begin_year_pointer, end_year_pointer, season1))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\src\Process-Data\..\Utils\tools.py", line 30, in get_json_data
    raw_data = requests.get(url, headers=data_headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NBA-Machine-Learning-Sports-Betting\NBA\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
(NBA) PS C:\NBA-Machine-Learning-Sports-Betting\src\Process-Data> `

**Comment by STRATZ-Ken** [comment]
Pretty sure this is due to the overloaded NBA Stats API.  Often times my requests take about 18-30 seconds to respond. At this point I just put a timeout of 5 seconds, and keep force retrying until I get a quick response.  Annoying but effective.
