### ISSUE TITLE
Predictions don't work why?

### ISSUE THREAD

**Issue by Gxent** [kyleskom/NBA-Machine-Learning-Sports-Betting#285]
2023-10-02 03:33:32.873028: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-02 03:33:35.568551: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-10-02 03:33:35.571847: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-10-02 03:33:35.571896: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-10-02 03:33:38.706681: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-10-02 03:33:38.706758: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
------------------fanduel odds data------------------
Dallas Mavericks (None) @ Minnesota Timberwolves (None)
---------------XGBoost Model Predictions---------------
Minnesota Timberwolves (62.2%) vs Dallas Mavericks: OVER None (95.8%)
---------------------Expected Value--------------------
Traceback (most recent call last):
  File "/content/main.py", line 132, in <module>
    main()
  File "/content/main.py", line 116, in main
    XGBoost_Runner.xgb_runner(data, todays_games_uo, frame_ml, games, home_team_odds, away_team_odds, args.kc)
  File "/content/src/Predict/XGBoost_Runner.py", line 89, in xgb_runner
    bankroll_fraction_home = bankroll_descriptor + str(kc.calculate_kelly_criterion(home_team_odds[count], ml_predictions_array[count][0][1])) + '%'
  File "/content/src/Utils/Kelly_Criterion.py", line 15, in calculate_kelly_criterion
    decimal_odds = american_to_decimal(american_odds)
  File "/content/src/Utils/Kelly_Criterion.py", line 5, in american_to_decimal
    if american_odds >= 100:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by kyleskom** [comment]
Because the season hasten started yet and there are no games today.
