### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Gxent** [kyleskom/NBA-Machine-Learning-Sports-Betting#292]
2023-10-07 01:02:56.382600: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-07 01:02:58.002907: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
------------------fanduel odds data------------------
Minnesota Timberwolves (-118) @ Dallas Mavericks (-104)
Los Angeles Lakers (104) @ Golden State Warriors (-128)
Traceback (most recent call last):
  File "/content/main.py", line 132, in <module>
    main()
  File "/content/main.py", line 104, in main
    data, todays_games_uo, frame_ml, home_team_odds, away_team_odds = createTodaysGames(games, df, odds)
  File "/content/main.py", line 56, in createTodaysGames
    last_home_date = home_games.loc[schedule_df['Date'] <= datetime.today()].sort_values('Date',ascending=False).head(1)['Date'].iloc[0]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by kyleskom** [comment]
Will look into this as games happen.

**Comment by Gxent** [comment]
Ok bro thx! 👍🏻
