### ISSUE TITLE
NONE Fanduel Odds Data

### ISSUE THREAD

**Issue by benjaminrbarnett** [kyleskom/NBA-Machine-Learning-Sports-Betting#307]
Hey Y'all, 

I am having an issue loading Fanduel Odds Data into the Google Colab with this code: ! python3 main.py -xgb -odds=fanduel -kc. Here is the response that I am getting:  

2023-10-20 02:14:47.028870: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-20 02:14:48.002214: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-20 02:14:50.005514: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-20 02:14:50.050033: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-20 02:14:50.050430: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-20 02:14:50.051352: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-20 02:14:50.051666: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-20 02:14:50.051943: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-20 02:14:51.072182: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-20 02:14:51.072481: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-20 02:14:51.072677: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-20 02:14:51.072818: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2023-10-20 02:14:51.072862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13692 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
------------------fanduel odds data------------------
Atlanta Hawks (None) @ Philadelphia 76ers (None)
Cleveland Cavaliers (None) @ Indiana Pacers (None)
Washington Wizards (None) @ Toronto Raptors (None)
Memphis Grizzlies (None) @ Milwaukee Bucks (None)
Detroit Pistons (None) @ Dallas Mavericks (None)
Miami Heat (None) @ Houston Rockets (None)
San Antonio Spurs (None) @ Golden State Warriors (None)
---------------XGBoost Model Predictions---------------
Philadelphia 76ers (70.8%) vs Atlanta Hawks: OVER None (91.5%)
Indiana Pacers vs Cleveland Cavaliers (62.2%): OVER None (97.0%)
Toronto Raptors (72.1%) vs Washington Wizards: OVER None (89.4%)
Milwaukee Bucks (64.6%) vs Memphis Grizzlies: OVER None (97.8%)
Dallas Mavericks (77.4%) vs Detroit Pistons: OVER None (91.3%)
Houston Rockets vs Miami Heat (71.2%): OVER None (67.2%)
Golden State Warriors (81.8%) vs San Antonio Spurs: OVER None (97.9%)
------------Expected Value & Kelly Criterion-----------
Traceback (most recent call last):
  File "/content/main.py", line 140, in <module>
    main()
  File "/content/main.py", line 120, in main
    XGBoost_Runner.xgb_runner(data, todays_games_uo, frame_ml, games, home_team_odds, away_team_odds, args.kc)
  File "/content/src/Predict/XGBoost_Runner.py", line 89, in xgb_runner
    bankroll_fraction_home = bankroll_descriptor + str(kc.calculate_kelly_criterion(home_team_odds[count], ml_predictions_array[count][0][1])) + '%'
  File "/content/src/Utils/Kelly_Criterion.py", line 15, in calculate_kelly_criterion
    decimal_odds = american_to_decimal(american_odds)
  File "/content/src/Utils/Kelly_Criterion.py", line 5, in american_to_decimal
    if american_odds >= 100:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by Baaios** [comment]
Replace with the following:

#Remove Preexisting Files
! rm -rf NBA-Machine-Learning-Sports-Betting
! rm -rf *

#Bootstrap Files
! git clone https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git
! mv -v ./NBA-Machine-Learning-Sports-Betting/* .
! pip3 install colorama
! pip3 install pandas
! pip3 install sbrscrape
! pip3 install tensorflow==2.11.0
! pip3 install tensorflow-meta
! pip3 install xgboost
! pip3 install tqdm
! pip3 install flask
! pip3 install scikit-learn

#Clear Bootstrap Logs
from IPython.display import clear_output
clear_output()

print("Successful Bootstrap!!!")
