### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by hatsonsale** [kyleskom/NBA-Machine-Learning-Sports-Betting#314]
2023-10-25 11:18:11.895631: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2023-10-25 11:18:11.895653: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2023-10-25 11:18:11.895659: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2023-10-25 11:18:11.895862: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-10-25 11:18:11.896199: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
------------------draftkings odds data------------------
Atlanta Hawks (-170) @ Charlotte Hornets (142)
Washington Wizards (220) @ Indiana Pacers (-270)
Boston Celtics (-166) @ New York Knicks (140)
Houston Rockets (142) @ Orlando Magic (-170)
Cleveland Cavaliers (-115) @ Brooklyn Nets (-105)
Detroit Pistons (320) @ Miami Heat (-410)
Minnesota Timberwolves (-115) @ Toronto Raptors (-105)
Oklahoma City Thunder (-108) @ Chicago Bulls (-112)
New Orleans Pelicans (-110) @ Memphis Grizzlies (-110)
Sacramento Kings (-125) @ Utah Jazz (105)
Dallas Mavericks (-162) @ San Antonio Spurs (136)
Portland Trail Blazers (320) @ LA Clippers (-410)
Expecting value: line 1 column 1 (char 0)
0
/Users/nikitashiryaev/PycharmProjects/NBA-Machine-Learning-Sports-Betting/main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
Traceback (most recent call last):
  File "/Users/nikitashiryaev/PycharmProjects/NBA-Machine-Learning-Sports-Betting/main.py", line 140, in <module>
    main()
  File "/Users/nikitashiryaev/PycharmProjects/NBA-Machine-Learning-Sports-Betting/main.py", line 112, in main
    data, todays_games_uo, frame_ml, home_team_odds, away_team_odds = createTodaysGames(games, df, odds)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikitashiryaev/PycharmProjects/NBA-Machine-Learning-Sports-Betting/main.py", line 72, in createTodaysGames
    home_team_series = df.iloc[team_index_current.get(home_team)]
                       ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikitashiryaev/PycharmProjects/NBA-Machine-Learning-Sports-Betting/venv/lib/python3.11/site-packages/pandas/core/indexing.py", line 1153, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikitashiryaev/PycharmProjects/NBA-Machine-Learning-Sports-Betting/venv/lib/python3.11/site-packages/pandas/core/indexing.py", line 1714, in _getitem_axis
    self._validate_integer(key, axis)
  File "/Users/nikitashiryaev/PycharmProjects/NBA-Machine-Learning-Sports-Betting/venv/lib/python3.11/site-packages/pandas/core/indexing.py", line 1647, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by ethan-hurst** [comment]
It looks like metal didn't love the version you're on for tensor flow. Maybe drop a minor version and try rebuild your deps?
