### ISSUE TITLE
Google colab sbrcrape not found

### ISSUE THREAD

**Issue by P1sta** [kyleskom/NBA-Machine-Learning-Sports-Betting#332]
Hi when i pop it into google colab I get this error.

Any help?

2023-10-30 11:46:22.721736: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/main.py", line 8, in <module>
    from src.DataProviders.SbrOddsProvider import SbrOddsProvider
  File "/content/src/DataProviders/SbrOddsProvider.py", line 1, in <module>
    from sbrscrape import Scoreboard
ModuleNotFoundError: No module named 'sbrscrape'

**Comment by thprtm** [comment]
How did you solve it?
