### ISSUE TITLE
OSError: No file or directory found at Models/NN_Models/Trained-Model-ML-1680133120.689445

### ISSUE THREAD

**Issue by adeka299aaa** [kyleskom/NBA-Machine-Learning-Sports-Betting#365]
2023-11-19 14:30:35.417954: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-19 14:30:35.418035: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-19 14:30:35.418075: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-19 14:30:35.427549: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-19 14:30:36.795031: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/NBA-Machine-Learning-Sports-Betting/main.py", line 9, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "/content/NBA-Machine-Learning-Sports-Betting/src/Predict/NN_Runner.py", line 12, in <module>
    model = load_model('Models/NN_Models/Trained-Model-ML-1680133120.689445')
  File "/usr/local/lib/python3.10/dist-packages/keras/src/saving/saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/src/saving/legacy/save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at Models/NN_Models/Trained-Model-ML-1680133120.689445

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/79244225/1505cdcf-22de-4d7d-b98b-480b4e8d0d8b)

**Comment by Skysafe64** [comment]
Hi! Thanks for explaining the issue you're facing thoroughly so that we can assist you effectively. Sending a screenshot and copying what we see in the screenshot won't help us in providing assistance tailored to your needs.

**Comment by kyleskom** [comment]
try https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/issues/344#issuecomment-1821809331
