### ISSUE TITLE
OSError: Cannot parse keras metadata at path Models/NN_Models/Trained-Model-ML-1699315388.285516\keras_metadata.pb: Received error: Error parsing message

### ISSUE THREAD

**Issue by d3gzz** [kyleskom/NBA-Machine-Learning-Sports-Betting#372]
I got this error, i dont know what to do :/

C:\Users\DEGZ\Desktop\NBA\NBA-Machine-Learning-Sports-Betting>python main.py -xgb -odds=fanduel
Traceback (most recent call last):
  File "C:\Users\DEGZ\Desktop\NBA\NBA-Machine-Learning-Sports-Betting\main.py", line 9, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "C:\Users\DEGZ\Desktop\NBA\NBA-Machine-Learning-Sports-Betting\src\Predict\NN_Runner.py", line 12, in <module>
    model = load_model('Models/NN_Models/Trained-Model-ML-1699315388.285516')
  File "C:\Users\DEGZ\AppData\Roaming\Python\Python310\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\DEGZ\AppData\Roaming\Python\Python310\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\DEGZ\AppData\Roaming\Python\Python310\site-packages\keras\src\saving\legacy\saved_model\load.py", line 113, in load
    raise IOError(
OSError: Cannot parse keras metadata at path Models/NN_Models/Trained-Model-ML-1699315388.285516\keras_metadata.pb: Received error: Error parsing message

C:\Users\DEGZ\Desktop\NBA\NBA-Machine-Learning-Sports-Betting>python --version
Python 3.10.0

**Comment by d3gzz** [comment]
Solved, just delete Models folder, then redownload it again
