### ISSUE TITLE
Create_Games

### ISSUE THREAD

**Issue by egamxmx** [kyleskom/NBA-Machine-Learning-Sports-Betting#409]
When creating the games it sends an error, and it does not send it:

C:\Python310\nba\NBA-Machine-Learning-Sports-Betting\src\Process-Data>python -m Create_Games
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 11/13 [01:03<00:11,  5.79s/it]
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\nba\NBA-Machine-Learning-Sports-Betting\src\Process-Data\Create_Games.py", line 90, in <module>
    home_team_series = team_df.iloc[team_index_current.get(home_team)]
  File "C:\Python310\lib\site-packages\pandas\core\indexing.py", line 1153, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Python310\lib\site-packages\pandas\core\indexing.py", line 1711, in _getitem_axis
    raise TypeError("Cannot index by location index with a non-integer key")
TypeError: Cannot index by location index with a non-integer key

**Comment by Scandianis** [comment]
https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/issues/403

**Comment by HyakuzaO** [comment]
Follow @Scandianis topic #403 , that solution will fix that.

**Comment by egamxmx** [comment]
thanks, it solve
