### ISSUE TITLE
Table: teams_2023-24-3-1 from today

### ISSUE THREAD

**Issue by egamxmx** [kyleskom/NBA-Machine-Learning-Sports-Betting#413]
last time I added "if home_team not in ['Eastern']:" but today it does not find today's table

C:\Python310\nba\NBA-Machine-Learning-Sports-Betting\src\Process-Data>python -m Create_Games
 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 11/12 [00:59<00:05,  5.45s/it]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pandas\io\sql.py", line 2264, in execute
    cur.execute(sql, *args)
sqlite3.OperationalError: no such table: teams_2023-24-3-1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\nba\NBA-Machine-Learning-Sports-Betting\src\Process-Data\Create_Games.py", line 62, in <module>
    team_df = pd.read_sql_query(f"select * from \"teams_{year}-{month}-{day}\"", teams_con, index_col="index")
  File "C:\Python310\lib\site-packages\pandas\io\sql.py", line 486, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Python310\lib\site-packages\pandas\io\sql.py", line 2328, in read_query
    cursor = self.execute(sql, params)
  File "C:\Python310\lib\site-packages\pandas\io\sql.py", line 2276, in execute
    raise ex from exc
pandas.errors.DatabaseError: **Execution failed on sql 'select * from "teams_2023-24-3-1"': no such table: teams_2023-24-3-1**

**Comment by Scandianis** [comment]
Solved here:

https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/issues/412

**Comment by egamxmx** [comment]
it works! if month1 == 2 and day1 > 29: 

thanks
