### ISSUE TITLE
AttributeError: 'Scoreboard' object has no attribute 'games'

### ISSUE THREAD

**Issue by jinpengchina** [kyleskom/NBA-Machine-Learning-Sports-Betting#74]
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
2023-01-30 23:32:49.267832: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-01-30 23:32:49.267941: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (800dfac52b9b): /proc/driver/nvidia/version does not exist
2023-01-30 23:32:49.268938: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
An error occurred: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    main()
  File "main.py", line 62, in main
    odds = SbrOddsProvider(sportsbook=args.odds).get_odds()
  File "/content/src/DataProviders/SbrOddsProvider.py", line 13, in __init__
    self.games = Scoreboard(sport="NBA").games
AttributeError: 'Scoreboard' object has no attribute 'games'

==============================================================
i run code in google colab 
==============================================================

#Remove Preexisting Files
! rm -rf NBA-Machine-Learning-Sports-Betting
! rm -rf *

#Bootstrap Files
! git clone https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git
! mv -v ./NBA-Machine-Learning-Sports-Betting/* .
! pip3 install -r requirements.txt

#Clear Bootstrap Logs
from IPython.display import clear_output 
clear_output()

print("Successful Bootstrap!!!")

!python3 main.py -A -odds=fanduel

**Comment by kyleskom** [comment]
Resolved. Try again.
