### ISSUE TITLE
Im getting this error

### ISSUE THREAD

**Issue by dvdrbls** [kyleskom/NBA-Machine-Learning-Sports-Betting#9]
= RESTART: C:\Users\Dell\Desktop\NBA-Machine-Learning-Sports-Betting\Test\Test_Current_Season.py
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\NBA-Machine-Learning-Sports-Betting\Test\Test_Current_Season.py", line 6, in <module>
    model = load_model('../Models/Trained-Model-ML')
  File "C:\Python38\lib\site-packages\tensorflow\python\keras\saving\save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "C:\Python38\lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 121, in load
    meta_graph_def = loader_impl.parse_saved_model(path).meta_graphs[0]
  File "C:\Python38\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 113, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: ../Models/Trained-Model-ML\{saved_model.pbtxt|saved_model.pb}

In there there is only a (l('../Models/Trained-Model-ML') file named saved_model.pb

**Comment by kyleskom** [comment]
I aww tour using `NBA-Machine-Learning-Sports-Betting\Test\Test_Current_Season.py`. I suspect the model I was using for that testing was an old model and never updated that file.
